language: java
jdk: 
	-oraclejdk11
before_install:
	- sudo apt-get update
	- cd app/
	- echo "Let's Start Maven Package!"
	- mvn clean package
	- cd ..
	- echo "We are in the Docker folder!"
script:
	- docker-compose build
before_deploy:
	echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --passworkd-stdin
deploy:
	provider: script
	script: 
		docker tag docker-to-with-java:latest marcoinforlube/docker-to-with-java:latest;
		docker push marcoinforlube/docker-to-with-java:latest;
	on:
		branch: master
notifications:
	email: false